version: "3.9"
networks:
  local_prjctnet:
    external: true

services:
  backend:
    build: .
    image: harbor.cubexs.dev/prjctrepo/backend

  backend-run:
    image: golang:1.19.4-alpine3.17
    container_name: backend
    volumes:
      - ./src:/app/src
      - ./scripts/modd.sh:/app/scripts/modd.sh
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./modd-run.conf:/app/modd-run.conf
    networks:
      - local_prjctnet
    command: ["sh", "-c", "cd /app/scripts && ./modd.sh run"]

  backend-unit-tests:
    image: golang:1.19.4-alpine3.17
    container_name: backend-test
    volumes:
      - ./src:/app/src
      - ./scripts/modd.sh:/app/scripts/modd.sh
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./modd-dev.conf:/app/modd-dev.conf
    networks:
      - local_prjctnet
    command: ["sh", "-c", "cd /app/scripts && ./modd.sh dev"]
